// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW_lk5h8SgTOLBzV3sf1trFCurfIHD6aY',
    appId: '1:359773799300:web:02e6789755d98355fc53d1',
    messagingSenderId: '359773799300',
    projectId: 'fir-flutter-codelab-c15c4',
    authDomain: 'fir-flutter-codelab-c15c4.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-c15c4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQNX5OMy-6vcffKGeJ_2gI5UfSRqyIGcw',
    appId: '1:359773799300:android:bc04d3ae7aa886e0fc53d1',
    messagingSenderId: '359773799300',
    projectId: 'fir-flutter-codelab-c15c4',
    storageBucket: 'fir-flutter-codelab-c15c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8I2VMMG6ss5DSQf-cK7mGu-KFe4GHcQ4',
    appId: '1:359773799300:ios:b83a6fab29e3fcb6fc53d1',
    messagingSenderId: '359773799300',
    projectId: 'fir-flutter-codelab-c15c4',
    storageBucket: 'fir-flutter-codelab-c15c4.appspot.com',
    iosClientId: '359773799300-bjmu8m6d3nf4amm9vom6iu7rn5f1b7un.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8I2VMMG6ss5DSQf-cK7mGu-KFe4GHcQ4',
    appId: '1:359773799300:ios:b83a6fab29e3fcb6fc53d1',
    messagingSenderId: '359773799300',
    projectId: 'fir-flutter-codelab-c15c4',
    storageBucket: 'fir-flutter-codelab-c15c4.appspot.com',
    iosClientId: '359773799300-bjmu8m6d3nf4amm9vom6iu7rn5f1b7un.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
